# Generated by Django 5.0.6 on 2024-07-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_create_initial_spaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='office_type',
            field=models.CharField(choices=[('single', 'Single Office for 1 Person'), ('multiple', 'Office for Multiple Persons'), ('meeting', 'Meeting Room'), ('lab', 'Lab with PCs'), ('suite', 'Private Office Suite')], default='single', max_length=15),
        ),
    ]
