# Generated by Django 5.0.6 on 2024-07-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_pendingreservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingReservation',
        ),
    ]
