# Generated by Django 5.0.6 on 2024-08-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='space',
            name='office_type',
            field=models.CharField(choices=[('single', 'Single Office for 1 Person'), ('multiple', 'Office for Multiple Persons'), ('meeting', 'Meeting Room'), ('lab', 'Lab with PCs'), ('suite', 'Private Office Suite'), ('coworking', 'Co-working Space'), ('hotdesk', 'Hot Desk Area'), ('conference', 'Conference Room'), ('studio', 'Creative Studio'), ('training', 'Training Room')], default='single', max_length=15),
        ),
    ]
